from enum import Enum

ACCESS_TOKEN_VAR_NAMES = {
    'gitlab.com': 'GITLAB_ACCESS_TOKEN',
    'github.com': 'GITHUB_OAUTH_TOKEN',
    'DEFAULT': 'GIT_TOKEN',
}


class CloningStates(Enum):
    NOT_STARTED = 'NOT_STARTED'
    CLONING = 'CLONING'
    CLONED = 'CLONED'
    SOURCE_BRANCH_DOES_NOT_EXIST = 'SOURCE_BRANCH_DOES_NOT_EXIST'
    ACCESS_TOKEN_NOT_PROVIDED = 'ACCESS_TOKEN_NOT_PROVIDED'
    NOT_FOUND = 'NOT_FOUND'
    SKIPPED = 'SKIPPED'
    DIRECTORY_NOT_EMPTY = 'DIRECTORY_NOT_EMPTY'


class ModificationState(Enum):
    NOT_STARTED = 'NOT_STARTED'
    GOT_EXCEPTION = 'GOT_EXCEPTION'
    MODIFYING = 'MODIFYING'
    MODIFIED = 'MODIFIED'
    NO_FILES_CHANGED = 'NO_FILES_CHANGED'
    PUSHED_TO_REMOTE = 'PUSHED_TO_REMOTE'


class PullRequestStates(Enum):
    NOT_STARTED = 'NOT_STARTED'
    NOT_CREATED = 'NOT_CREATED'
    CREATING = 'CREATING'
    CREATED = 'CREATED'
    GOT_BAD_RESPONSE = 'GOT_BAD_RESPONSE'
    MERGED = 'MERGED'
