1: venv312
	autogit -r repos.txt add_hello_to_readme.py

2: venv312
	autogit -r repos.txt -m "Bump Python version 2" bump_python_version.py


venv312:
	python3.12 -m venv venv312
	venv312/bin/pip install autogit>=0.0.26
